import { TIER_CONSTANTS } from "../constants/tiers";

export const franchiseMetadata = [
    { prefix: "UPS",
        discordUrl: "https://discord.gg/VPdMevRF",
        inceptionSeason: 7,
        trophies: [
        { season: 14, tier: TIER_CONSTANTS.Elite},
        { season: 14, tier: TIER_CONSTANTS.Challenger},
        { season: 12, tier: TIER_CONSTANTS.Premier},
        { season: 12, tier: TIER_CONSTANTS.Challenger},
        { season: 11, tier: TIER_CONSTANTS.Recruit},
        { season: 10, tier: TIER_CONSTANTS.Prospect},
        { season: 9, tier: TIER_CONSTANTS.Elite},
        { season: 8, tier: TIER_CONSTANTS.Premier},
        { season: 7, tier: TIER_CONSTANTS.Challenger},
    ], },
    { prefix: "WET",
        discordUrl: "https://discord.gg/hWn2DGhf",
        inceptionSeason: 1,
        trophies: [
        { season: 14, tier: TIER_CONSTANTS.Prospect},
        { season: 13, tier: TIER_CONSTANTS.Contender},
        { season: 11, tier: TIER_CONSTANTS.Contender},
    ]},
    { prefix: "H4K",
        discordUrl: "",
        inceptionSeason: 1,
        trophies: [
        { season: 14, tier: TIER_CONSTANTS.Contender},
        { season: 13, tier: TIER_CONSTANTS.Elite},
        { season: 12, tier: TIER_CONSTANTS.Elite},
        { season: 11, tier: TIER_CONSTANTS.Elite},
        { season: 10, tier: TIER_CONSTANTS.Elite},
    ]},
    { prefix: "OS",
        discordUrl: "",
        inceptionSeason: 1,
        trophies: [
        { season: 8, tier: TIER_CONSTANTS.Challenger},
        { season: 7, tier: TIER_CONSTANTS.Prospect},
        { season: 6, tier: "Minor"},
    ]},
    { prefix: "HG",
        discordUrl: "",
        inceptionSeason: 1,
        trophies: [
        { season: 14, tier: TIER_CONSTANTS.Premier},
        { season: 13, tier: TIER_CONSTANTS.Challenger},
        { season: 10, tier: TIER_CONSTANTS.Premier},
        { season: 9, tier: TIER_CONSTANTS.Challenger},
        { season: 7, tier: TIER_CONSTANTS.Premier},
        { season: 7, tier: TIER_CONSTANTS.Elite},
    ]},
    { prefix: "SAV",
        discordUrl: "https://discord.gg/BAbNKr55",
        inceptionSeason: 1,
        trophies: [
        { season: 12, tier: TIER_CONSTANTS.Recruit},
        { season: 9, tier: TIER_CONSTANTS.Contender},
    ]},
    { prefix: "ATL",
        discordUrl: "",
        inceptionSeason: 1,
        trophies: [
        { season: 13, tier: TIER_CONSTANTS.Prospect},
        { season: 10, tier: TIER_CONSTANTS.Challenger},
    ]},
    { prefix: "AVI",
        discordUrl: "https://discord.gg/uXHms59b",
        inceptionSeason: 1,
        trophies: [
        { season: 13, tier: TIER_CONSTANTS.Premier},
        { season: 11, tier: TIER_CONSTANTS.Prospect},
        { season: 8, tier: TIER_CONSTANTS.Elite},
    ]},
    { prefix: "NAN",
        discordUrl: "",
        inceptionSeason: 1,
        trophies: [
        { season: 11, tier: TIER_CONSTANTS.Challenger},
        { season: 13, tier: TIER_CONSTANTS.Recruit}
    ]},
    { prefix: "COW",
        discordUrl: "",
        inceptionSeason: 1,
        trophies: [
        { season: 11, tier: TIER_CONSTANTS.Premier},
    ]},
    { prefix: "ABW",
        discordUrl: "",
        inceptionSeason: 1,
        trophies: [
        { season: 14, tier: TIER_CONSTANTS.Recruit},
    ]},
    { prefix: "dB",
        discordUrl: "https://discord.gg/sp89uQbX",
        inceptionSeason: 1,
        trophies: [
    ]},
] 